services:
  backend:
    environment:
      - FLASK_ENV=development
      - CORS_ORIGINS=*

  frontend-dev:
    container_name: podly_frontend_dev
    image: node:18-alpine
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5002"
    ports:
      - 5002:5002
    environment:
      - VITE_API_URL=http://localhost:5001
      - NODE_ENV=development
    depends_on:
      - backend 