services:
  podly:
    container_name: podly_app
    build: .
    volumes:
      - ./config:/app/config
      - ./in:/app/in
      - ./srv:/app/srv
      - ./src/instance:/app/src/instance
    ports:
      - 5001:5001
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:--1}
      - CORS_ORIGINS=*
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5001/')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
