services:
  podly:
    build: .
    container_name: podly_app
    ports:
      - "5001:5001"
    volumes:
      - ./in:/app/in
      - ./srv:/app/srv
      - ./config:/app/config
      - ./processing:/app/processing
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
