services:
  podly:
    container_name: podly-pure-podcasts
    image: podly-pure-podcasts
    volumes:
      - ./config:/app/config
      - ./in:/app/in
      - ./srv:/app/srv
      - ./src/instance:/app/src/instance
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=${BASE_IMAGE:-python:3.11-slim}
        - CUDA_VERSION=${CUDA_VERSION:-12.4.1}
        - USE_GPU=${USE_GPU:-false}
        - USE_GPU_NVIDIA=${USE_GPU_NVIDIA:-false}
        - USE_GPU_AMD=${USE_GPU_AMD:-false}
        - LITE_BUILD=${LITE_BUILD:-false}
    ports:
      - 5001:5001
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:--1}
      - CORS_ORIGINS=*
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5001/')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: podly-pure-podcasts-network
