services:
  podly:
    container_name: podly
    ports:
      - 5001:5001
    build: .
    volumes:
      - ./config:/app/config
      - ./in:/app/in
      - ./srv:/app/srv
      - ./src/instance:/app/src/instance
    environment:
      - FLASK_ENV=development
      - CORS_ORIGINS=*
    restart: unless-stopped

networks:
  default:
    name: podly_network
