services:
  podly:
    build: .
    container_name: podly
    ports:
      - 5001:5001
    volumes:
      - .:/app
      - ./in:/app/in
      - ./srv:/app/srv
      - ./processing:/app/processing
    environment:
      - FLASK_ENV=development
      - CORS_ORIGINS=*
    restart: unless-stopped

networks:
  default:
    name: podly_network
