[tool.pylint]
init-hook = 'import sys; sys.path.append("./src")'

disable = [
    "logging-fstring-interpolation",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-locals",
    "unspecified-encoding",
    "line-too-long",
    "too-many-return-statements"
]

[tool.mypy]
warn_unused_ignores = true
strict = true
mypy_path = "src"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88
float_to_top = true
