"""feed_access

Revision ID: 0d954a44fa8e
Revises: 91ff431c832e
Create Date: 2025-11-04 21:43:07.716121

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0d954a44fa8e"
down_revision = "91ff431c832e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feed_access_token",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token_id", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feed_access_token", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feed_access_token_token_id"), ["token_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_access_token", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feed_access_token_token_id"))

    op.drop_table("feed_access_token")
    # ### end Alembic commands ###
