"""env_hash

Revision ID: 16311623dd58
Revises: 5bccc39c9685
Create Date: 2025-12-14 10:32:15.843860

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16311623dd58"
down_revision = "5bccc39c9685"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("env_config_hash", sa.String(length=64), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("env_config_hash")

    # ### end Alembic commands ###
