"""stripe

Revision ID: 185d3448990e
Revises: 35b12b2d9feb
Create Date: 2025-12-10 21:51:55.888021

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "185d3448990e"
down_revision = "35b12b2d9feb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table("credit_transaction"):
        indexes = [i["name"] for i in inspector.get_indexes("credit_transaction")]
        with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
            if "ix_credit_transaction_feed_id" in indexes:
                batch_op.drop_index(batch_op.f("ix_credit_transaction_feed_id"))
            if "ix_credit_transaction_post_id" in indexes:
                batch_op.drop_index(batch_op.f("ix_credit_transaction_post_id"))
            if "ix_credit_transaction_user_created" in indexes:
                batch_op.drop_index(batch_op.f("ix_credit_transaction_user_created"))
            if "ix_credit_transaction_user_id" in indexes:
                batch_op.drop_index(batch_op.f("ix_credit_transaction_user_id"))

        op.drop_table("credit_transaction")

    if inspector.has_table("app_settings"):
        columns = [c["name"] for c in inspector.get_columns("app_settings")]
        with op.batch_alter_table("app_settings", schema=None) as batch_op:
            if "minutes_per_credit" in columns:
                batch_op.drop_column("minutes_per_credit")

    if inspector.has_table("users"):
        columns = [c["name"] for c in inspector.get_columns("users")]
        with op.batch_alter_table("users", schema=None) as batch_op:
            if "feed_allowance" not in columns:
                batch_op.add_column(
                    sa.Column("feed_allowance", sa.Integer(), nullable=False)
                )
            if "feed_subscription_status" not in columns:
                batch_op.add_column(
                    sa.Column(
                        "feed_subscription_status", sa.String(length=32), nullable=False
                    )
                )
            if "stripe_customer_id" not in columns:
                batch_op.add_column(
                    sa.Column("stripe_customer_id", sa.String(length=64), nullable=True)
                )
            if "stripe_subscription_id" not in columns:
                batch_op.add_column(
                    sa.Column(
                        "stripe_subscription_id", sa.String(length=64), nullable=True
                    )
                )
            if "credits_balance" in columns:
                batch_op.drop_column("credits_balance")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table("users"):
        columns = [c["name"] for c in inspector.get_columns("users")]
        with op.batch_alter_table("users", schema=None) as batch_op:
            if "credits_balance" not in columns:
                batch_op.add_column(
                    sa.Column(
                        "credits_balance",
                        sa.NUMERIC(precision=12, scale=2),
                        nullable=False,
                    )
                )
            if "stripe_subscription_id" in columns:
                batch_op.drop_column("stripe_subscription_id")
            if "stripe_customer_id" in columns:
                batch_op.drop_column("stripe_customer_id")
            if "feed_subscription_status" in columns:
                batch_op.drop_column("feed_subscription_status")
            if "feed_allowance" in columns:
                batch_op.drop_column("feed_allowance")

    if inspector.has_table("app_settings"):
        columns = [c["name"] for c in inspector.get_columns("app_settings")]
        with op.batch_alter_table("app_settings", schema=None) as batch_op:
            if "minutes_per_credit" not in columns:
                batch_op.add_column(
                    sa.Column(
                        "minutes_per_credit",
                        sa.INTEGER(),
                        server_default=sa.text("(60)"),
                        nullable=False,
                    )
                )

    if not inspector.has_table("credit_transaction"):
        op.create_table(
            "credit_transaction",
            sa.Column("id", sa.INTEGER(), nullable=False),
            sa.Column("user_id", sa.INTEGER(), nullable=False),
            sa.Column("feed_id", sa.INTEGER(), nullable=True),
            sa.Column("post_id", sa.INTEGER(), nullable=True),
            sa.Column("idempotency_key", sa.VARCHAR(length=128), nullable=True),
            sa.Column(
                "amount_signed", sa.NUMERIC(precision=12, scale=2), nullable=False
            ),
            sa.Column("type", sa.VARCHAR(length=32), nullable=False),
            sa.Column("note", sa.TEXT(), nullable=True),
            sa.Column("created_at", sa.DATETIME(), nullable=False),
            sa.ForeignKeyConstraint(
                ["feed_id"],
                ["feed.id"],
            ),
            sa.ForeignKeyConstraint(
                ["post_id"],
                ["post.id"],
            ),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("idempotency_key"),
        )
        with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_credit_transaction_user_id"), ["user_id"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_credit_transaction_user_created"),
                ["user_id", "created_at"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_credit_transaction_post_id"), ["post_id"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_credit_transaction_feed_id"), ["feed_id"], unique=False
            )

    # ### end Alembic commands ###
