"""cleanup_retention_days

Revision ID: 18c2402c9202
Revises: a6f5df1a50ac
Create Date: 2025-11-03 22:05:56.956113

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "18c2402c9202"
down_revision = "a6f5df1a50ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("post_cleanup_retention_days", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("post_cleanup_retention_days")

    # ### end Alembic commands ###
