"""Add language column to Post model

Revision ID: 28824cb334ac
Revises: ded4b70feadb
Create Date: 2025-04-19 11:40:02.375412

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "28824cb334ac"
down_revision = "ded4b70feadb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language", sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_column("language")

    # ### end Alembic commands ###
