"""per feed auto whitelist

Revision ID: 2e25a15d11de
Revises: 82cfcc8e0326
Create Date: 2026-01-12 12:47:42.611999

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e25a15d11de"
down_revision = "82cfcc8e0326"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "auto_whitelist_new_episodes_override", sa.Boolean(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_column("auto_whitelist_new_episodes_override")

    # ### end Alembic commands ###
