"""credits

Revision ID: 31d767deb401
Revises: 608e0b27fcda
Create Date: 2025-11-29 11:42:27.900494

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "31d767deb401"
down_revision = "608e0b27fcda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_transaction",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=True),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("amount_signed", sa.Numeric(precision=12, scale=1), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_credit_transaction_feed_id"), ["feed_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_credit_transaction_post_id"), ["post_id"], unique=False
        )
        batch_op.create_index(
            "ix_credit_transaction_user_created",
            ["user_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_credit_transaction_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "minutes_per_credit",
                sa.Integer(),
                nullable=False,
                server_default=sa.text("60"),
            )
        )

    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sponsor_user_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("sponsor_note", sa.Text(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_feed_sponsor_user_id"), ["sponsor_user_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_feed_sponsor_user_id",
            "users",
            ["sponsor_user_id"],
            ["id"],
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "credits_balance", sa.Numeric(precision=12, scale=1), nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("credits_balance")

    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_constraint("fk_feed_sponsor_user_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_feed_sponsor_user_id"))
        batch_op.drop_column("sponsor_note")
        batch_op.drop_column("sponsor_user_id")

    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("minutes_per_credit")

    with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_credit_transaction_user_id"))
        batch_op.drop_index("ix_credit_transaction_user_created")
        batch_op.drop_index(batch_op.f("ix_credit_transaction_post_id"))
        batch_op.drop_index(batch_op.f("ix_credit_transaction_feed_id"))

    op.drop_table("credit_transaction")
    # ### end Alembic commands ###
