"""credits

Revision ID: 31d767deb401
Revises: 608e0b27fcda
Create Date: 2025-11-29 11:42:27.900494

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "31d767deb401"
down_revision = "608e0b27fcda"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if "credit_transaction" not in existing_tables:
        op.create_table(
            "credit_transaction",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("feed_id", sa.Integer(), nullable=True),
            sa.Column("post_id", sa.Integer(), nullable=True),
            sa.Column("idempotency_key", sa.String(length=128), nullable=True),
            sa.Column(
                "amount_signed", sa.Numeric(precision=12, scale=1), nullable=False
            ),
            sa.Column("type", sa.String(length=32), nullable=False),
            sa.Column("note", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(
                ["feed_id"],
                ["feed.id"],
            ),
            sa.ForeignKeyConstraint(
                ["post_id"],
                ["post.id"],
            ),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("idempotency_key"),
        )
        with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_credit_transaction_feed_id"), ["feed_id"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_credit_transaction_post_id"), ["post_id"], unique=False
            )
            batch_op.create_index(
                "ix_credit_transaction_user_created",
                ["user_id", "created_at"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_credit_transaction_user_id"), ["user_id"], unique=False
            )

    if "app_settings" in existing_tables:
        app_columns = {col["name"] for col in inspector.get_columns("app_settings")}
        if "minutes_per_credit" not in app_columns:
            with op.batch_alter_table("app_settings", schema=None) as batch_op:
                batch_op.add_column(
                    sa.Column(
                        "minutes_per_credit",
                        sa.Integer(),
                        nullable=False,
                        server_default=sa.text("60"),
                    )
                )

    if "feed" in existing_tables:
        feed_columns = {col["name"] for col in inspector.get_columns("feed")}
        if "sponsor_user_id" not in feed_columns:
            with op.batch_alter_table("feed", schema=None) as batch_op:
                batch_op.add_column(
                    sa.Column("sponsor_user_id", sa.Integer(), nullable=True)
                )
                batch_op.add_column(sa.Column("sponsor_note", sa.Text(), nullable=True))
                batch_op.create_index(
                    batch_op.f("ix_feed_sponsor_user_id"),
                    ["sponsor_user_id"],
                    unique=False,
                )
                batch_op.create_foreign_key(
                    "fk_feed_sponsor_user_id",
                    "users",
                    ["sponsor_user_id"],
                    ["id"],
                )

    if "users" in existing_tables:
        user_columns = {col["name"] for col in inspector.get_columns("users")}
        if "credits_balance" not in user_columns:
            with op.batch_alter_table("users", schema=None) as batch_op:
                batch_op.add_column(
                    sa.Column(
                        "credits_balance",
                        sa.Numeric(precision=12, scale=1),
                        nullable=False,
                        server_default=sa.text("1"),
                    )
                )

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if "users" in existing_tables:
        user_columns = {col["name"] for col in inspector.get_columns("users")}
        if "credits_balance" in user_columns:
            with op.batch_alter_table("users", schema=None) as batch_op:
                batch_op.drop_column("credits_balance")

    if "feed" in existing_tables:
        feed_columns = {col["name"] for col in inspector.get_columns("feed")}
        if "sponsor_user_id" in feed_columns or "sponsor_note" in feed_columns:
            with op.batch_alter_table("feed", schema=None) as batch_op:
                if "fk_feed_sponsor_user_id" in {
                    fk["name"] for fk in inspector.get_foreign_keys("feed")
                }:
                    batch_op.drop_constraint(
                        "fk_feed_sponsor_user_id", type_="foreignkey"
                    )
                if "ix_feed_sponsor_user_id" in {
                    idx["name"] for idx in inspector.get_indexes("feed")
                }:
                    batch_op.drop_index(batch_op.f("ix_feed_sponsor_user_id"))
                if "sponsor_note" in feed_columns:
                    batch_op.drop_column("sponsor_note")
                if "sponsor_user_id" in feed_columns:
                    batch_op.drop_column("sponsor_user_id")

    if "app_settings" in existing_tables:
        app_columns = {col["name"] for col in inspector.get_columns("app_settings")}
        if "minutes_per_credit" in app_columns:
            with op.batch_alter_table("app_settings", schema=None) as batch_op:
                batch_op.drop_column("minutes_per_credit")

    if "credit_transaction" in existing_tables:
        with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
            existing_indexes = {
                idx["name"] for idx in inspector.get_indexes("credit_transaction")
            }
            if batch_op.f("ix_credit_transaction_user_id") in existing_indexes:
                batch_op.drop_index(batch_op.f("ix_credit_transaction_user_id"))
            if "ix_credit_transaction_user_created" in existing_indexes:
                batch_op.drop_index("ix_credit_transaction_user_created")
            if batch_op.f("ix_credit_transaction_post_id") in existing_indexes:
                batch_op.drop_index(batch_op.f("ix_credit_transaction_post_id"))
            if batch_op.f("ix_credit_transaction_feed_id") in existing_indexes:
                batch_op.drop_index(batch_op.f("ix_credit_transaction_feed_id"))

        op.drop_table("credit_transaction")
    # ### end Alembic commands ###
