"""landing page

Revision ID: 35b12b2d9feb
Revises: eb51923af483
Create Date: 2025-12-01 23:49:10.400190

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "35b12b2d9feb"
down_revision = "eb51923af483"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "enable_public_landing_page",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            ),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("enable_public_landing_page")

    # ### end Alembic commands ###
