"""migration

Revision ID: 3d232f215842
Revises: f7a4195e0953
Create Date: 2026-01-11 18:35:34.763013

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3d232f215842"
down_revision = "f7a4195e0953"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "enable_word_level_boundary_refinder",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.drop_column("enable_word_level_boundary_refinder")

    # ### end Alembic commands ###
