"""discord

Revision ID: 3eb0a3a0870b
Revises: 31d767deb401
Create Date: 2025-11-29 12:41:40.446049

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3eb0a3a0870b"
down_revision = "31d767deb401"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("discord_id", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(
            sa.Column("discord_username", sa.String(length=100), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_users_discord_id"), ["discord_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_discord_id"))
        batch_op.drop_column("discord_username")
        batch_op.drop_column("discord_id")

    # ### end Alembic commands ###
