"""add_last_active_to_user

Revision ID: 58b4eedd4c61
Revises: 73a6b9f9b643
Create Date: 2025-12-20 14:01:36.022682

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "58b4eedd4c61"
down_revision = "73a6b9f9b643"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_active", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("last_active")

    # ### end Alembic commands ###
