"""zero initial allowance

Revision ID: 5bccc39c9685
Revises: ab643af6472e
Create Date: 2025-12-12 14:21:35.530141

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5bccc39c9685"
down_revision = "ab643af6472e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
