"""stronger_access_token

Revision ID: 608e0b27fcda
Revises: f6d5fee57cc3
Create Date: 2025-11-05 21:27:10.923394

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "608e0b27fcda"
down_revision = "f6d5fee57cc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_access_token", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("token_secret", sa.String(length=128), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_access_token", schema=None) as batch_op:
        batch_op.drop_column("token_secret")

    # ### end Alembic commands ###
