"""Add image_url to Post model for episode thumbnails

Revision ID: 611dcb5d7f12
Revises: b038c2f99086
Create Date: 2025-05-25 13:39:49.168287

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "611dcb5d7f12"
down_revision = "b038c2f99086"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image_url", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("image_url")

    # ### end Alembic commands ###
