"""alternate feed ID

Revision ID: 6e0e16299dcb
Revises: 770771437280
Create Date: 2024-11-23 11:04:37.861614

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e0e16299dcb"
down_revision = "770771437280"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.add_column(sa.Column("alt_id", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_column("alt_id")

    # ### end Alembic commands ###
