"""allow_null_feed_id_for_aggregate_tokens

Revision ID: 73a6b9f9b643
Revises: 89d86978f407
Create Date: 2025-12-14 13:28:57.243239

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "73a6b9f9b643"
down_revision = "89d86978f407"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_access_token", schema=None) as batch_op:
        batch_op.alter_column("feed_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed_access_token", schema=None) as batch_op:
        batch_op.alter_column("feed_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
