"""discord settings

Revision ID: 7de4e57ec4bb
Revises: 3eb0a3a0870b
Create Date: 2025-11-29 12:47:45.289285

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7de4e57ec4bb"
down_revision = "3eb0a3a0870b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Text(), nullable=True),
        sa.Column("client_secret", sa.Text(), nullable=True),
        sa.Column("redirect_uri", sa.Text(), nullable=True),
        sa.Column("guild_ids", sa.Text(), nullable=True),
        sa.Column("allow_registration", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("discord_settings")
    # ### end Alembic commands ###
