"""gruanular credits

Revision ID: 802a2365976d
Revises: 7de4e57ec4bb
Create Date: 2025-11-29 19:10:18.950548

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "802a2365976d"
down_revision = "7de4e57ec4bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
        batch_op.alter_column(
            "amount_signed",
            existing_type=sa.NUMERIC(precision=12, scale=1),
            type_=sa.Numeric(precision=12, scale=2),
            existing_nullable=False,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "credits_balance",
            existing_type=sa.NUMERIC(precision=12, scale=1),
            type_=sa.Numeric(precision=12, scale=2),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "credits_balance",
            existing_type=sa.Numeric(precision=12, scale=2),
            type_=sa.NUMERIC(precision=12, scale=1),
            existing_nullable=False,
        )

    with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
        batch_op.alter_column(
            "amount_signed",
            existing_type=sa.Numeric(precision=12, scale=2),
            type_=sa.NUMERIC(precision=12, scale=1),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
