"""refined cuts

Revision ID: 82cfcc8e0326
Revises: 3d232f215842
Create Date: 2026-01-11 20:44:32.127284

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "82cfcc8e0326"
down_revision = "3d232f215842"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("refined_ad_boundaries", sa.JSON(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("refined_ad_boundaries_updated_at", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("refined_ad_boundaries_updated_at")
        batch_op.drop_column("refined_ad_boundaries")

    # ### end Alembic commands ###
