"""download_count

Revision ID: 91ff431c832e
Revises: 18c2402c9202
Create Date: 2025-11-03 23:24:04.934488

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "91ff431c832e"
down_revision = "18c2402c9202"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs_manager_run", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.drop_column("previous_run_id")

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("download_count", sa.Integer(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_username"), type_="unique")
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=False
        )
        batch_op.create_unique_constraint(batch_op.f("uq_users_username"), ["username"])

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("download_count")

    with op.batch_alter_table("jobs_manager_run", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("previous_run_id", sa.VARCHAR(length=36), nullable=True)
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    # ### end Alembic commands ###
