"""add_manual_feed_allowance_to_user

Revision ID: ab643af6472e
Revises: 185d3448990e
Create Date: 2025-12-12 14:06:14.400553

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab643af6472e"
down_revision = "185d3448990e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feed_sponsor_user_id"))
        batch_op.drop_constraint(
            batch_op.f("fk_feed_sponsor_user_id"), type_="foreignkey"
        )
        batch_op.drop_column("sponsor_user_id")
        batch_op.drop_column("sponsor_note")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("manual_feed_allowance", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("manual_feed_allowance")

    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sponsor_note", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("sponsor_user_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_feed_sponsor_user_id"), "users", ["sponsor_user_id"], ["id"]
        )
        batch_op.create_index(
            batch_op.f("ix_feed_sponsor_user_id"), ["sponsor_user_id"], unique=False
        )

    # ### end Alembic commands ###
