"""empty message

Revision ID: bae70e584468
Revises: 
Create Date: 2024-10-20 14:45:30.170794

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bae70e584468"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
