"""add autoprocess_on_download

Revision ID: e1325294473b
Revises: 73a6b9f9b643
Create Date: 2025-12-25 20:45:12.595954

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1325294473b"
down_revision = "73a6b9f9b643"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "autoprocess_on_download",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),  # ensure existing SQLite rows get a value
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("autoprocess_on_download")

    # ### end Alembic commands ###
