"""multiple supporters

Revision ID: eb51923af483
Revises: 802a2365976d
Create Date: 2025-12-01 22:25:13.104687

"""

from datetime import datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "eb51923af483"
down_revision = "802a2365976d"
branch_labels = None
depends_on = None


def _table_exists(table_name: str) -> bool:
    """Check if a table exists in the database."""
    connection = op.get_bind()
    inspector = inspect(connection)
    return table_name in inspector.get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table."""
    connection = op.get_bind()
    inspector = inspect(connection)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create feed_supporter table if it doesn't exist
    if not _table_exists("feed_supporter"):
        op.create_table(
            "feed_supporter",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("feed_id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(
                ["feed_id"],
                ["feed.id"],
            ),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint(
                "feed_id", "user_id", name="uq_feed_supporter_feed_user"
            ),
        )

    # Add columns to processing_job if they don't exist
    if not _column_exists("processing_job", "requested_by_user_id"):
        with op.batch_alter_table("processing_job", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column("requested_by_user_id", sa.Integer(), nullable=True)
            )
            batch_op.add_column(
                sa.Column("billing_user_id", sa.Integer(), nullable=True)
            )
            batch_op.create_foreign_key(
                "fk_processing_job_billing_user_id",
                "users",
                ["billing_user_id"],
                ["id"],
            )
            batch_op.create_foreign_key(
                "fk_processing_job_requested_by_user_id",
                "users",
                ["requested_by_user_id"],
                ["id"],
            )

    # Seed supporter rows for existing sponsors so they keep access permissions.
    connection = op.get_bind()
    feed_supporter_table = sa.table(
        "feed_supporter",
        sa.column("feed_id", sa.Integer),
        sa.column("user_id", sa.Integer),
        sa.column("created_at", sa.DateTime),
    )

    # Check which sponsor/feed combos already exist
    existing = set()
    result = connection.execute(sa.text("SELECT feed_id, user_id FROM feed_supporter"))
    for row in result:
        existing.add((row._mapping["feed_id"], row._mapping["user_id"]))

    result = connection.execute(
        sa.text(
            "SELECT id AS feed_id, sponsor_user_id FROM feed WHERE sponsor_user_id IS NOT NULL"
        )
    )
    inserts = []
    seen = set()
    for row in result:
        feed_id = row._mapping["feed_id"]
        user_id = row._mapping["sponsor_user_id"]
        if not user_id:
            continue
        key = (feed_id, user_id)
        if key in seen or key in existing:
            continue
        seen.add(key)
        inserts.append(
            {
                "feed_id": feed_id,
                "user_id": user_id,
                "created_at": datetime.utcnow(),
            }
        )
    if inserts:
        op.bulk_insert(feed_supporter_table, inserts)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("processing_job", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_processing_job_requested_by_user_id", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_processing_job_billing_user_id", type_="foreignkey"
        )
        batch_op.drop_column("billing_user_id")
        batch_op.drop_column("requested_by_user_id")

    op.drop_table("feed_supporter")
    # ### end Alembic commands ###
