"""add enable_boundary_refinement to llm_settings

Revision ID: f7a4195e0953
Revises: e1325294473b
Create Date: 2026-01-06 23:02:56.142954

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f7a4195e0953"
down_revision = "e1325294473b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "enable_boundary_refinement",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("1"),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.drop_column("enable_boundary_refinement")

    # ### end Alembic commands ###
