"""audio processing paths

Revision ID: fa3a95ecd67d
Revises: bae70e584468
Create Date: 2024-11-09 16:48:09.337029

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fa3a95ecd67d"
down_revision = "bae70e584468"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("unprocessed_audio_path", sa.Text(), nullable=True)
        )
        batch_op.add_column(sa.Column("processed_audio_path", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("processed_audio_path")
        batch_op.drop_column("unprocessed_audio_path")

    # ### end Alembic commands ###
