from __future__ import annotations

# Centralized default values for application configuration.
# Single source of truth for defaults across runtime, DB models, and Pydantic config.

# LLM defaults
LLM_DEFAULT_MODEL = "groq/openai/gpt-oss-120b"
OPENAI_DEFAULT_MAX_TOKENS = 4096
OPENAI_DEFAULT_TIMEOUT_SEC = 300
LLM_DEFAULT_MAX_CONCURRENT_CALLS = 3
LLM_DEFAULT_MAX_RETRY_ATTEMPTS = 5
LLM_ENABLE_TOKEN_RATE_LIMITING = False
LLM_MAX_INPUT_TOKENS_PER_CALL: int | None = None
LLM_MAX_INPUT_TOKENS_PER_MINUTE: int | None = None

# Whisper defaults
WHISPER_DEFAULT_TYPE = "groq"
WHISPER_LOCAL_MODEL = "base.en"
WHISPER_REMOTE_BASE_URL = "https://api.openai.com/v1"
WHISPER_REMOTE_MODEL = "whisper-1"
WHISPER_REMOTE_LANGUAGE = "en"
WHISPER_REMOTE_TIMEOUT_SEC = 600
WHISPER_REMOTE_CHUNKSIZE_MB = 24

WHISPER_GROQ_MODEL = "whisper-large-v3-turbo"
WHISPER_GROQ_LANGUAGE = "en"
WHISPER_GROQ_MAX_RETRIES = 3

# Processing defaults
PROCESSING_NUM_SEGMENTS_TO_INPUT_TO_PROMPT = 60

# Output defaults
OUTPUT_FADE_MS = 3000
OUTPUT_MIN_AD_SEGMENT_SEPARATION_SECONDS = 60
OUTPUT_MIN_AD_SEGMENT_LENGTH_SECONDS = 14
OUTPUT_MIN_CONFIDENCE = 0.8

# App defaults
APP_BACKGROUND_UPDATE_INTERVAL_MINUTE = 30
APP_AUTOMATICALLY_WHITELIST_NEW_EPISODES = True
APP_NUM_EPISODES_TO_WHITELIST_FROM_ARCHIVE_OF_NEW_FEED = 1
